name: Build

on: push

jobs:
  build and test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Check codestyle
        run: git ls-files *.{c,cpp,h} | xargs clang-format -i && git diff --exit-code

      - name: Build project file
        run: cmake -S . -B build/
      
      - name: Build application and test
        run: cmake --build build/
      
      - name: Run test
        run: ./build/test_list